### ISSUE TITLE
dataset for clef2022

### ISSUE THREAD

**Issue by wang-rui6** [pengfeiliHEU/MUMC#1]
Hello, can you provide a dataset for clef2022？

**Comment by xiaoconghao** [comment]
你好，请问你解决这个问题了吗

**Comment by wang-rui6** [comment]
> 你好，请问你解决这个问题了吗

没有

**Comment by pengfeiliHEU** [comment]
Hello, thank you for your interest in this work. If you cannot find the relevant dataset online, you can try contacting the authors of the dataset-related publications via email to request it. This is how I obtained it. Best of luck!

**Comment by xiaoconghao** [comment]
没有解决。已经转其他问题了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pengfeiliHEU/MUMC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月3日(星期天) 下午5:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pengfeiliHEU/MUMC] dataset for clef2022 (Issue #1)





   
你好，请问你解决这个问题了吗
  
没有
  
哥找到这个数据集了吗？应该联系谁获取呀
